Bug fix

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -29,30 +29,23 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - name: latest supported versions
-            os: ubuntu-latest
+          - os: ubuntu-latest
             python-version: '3.13'
 
-          - name: intermediate supported version
-            os: ubuntu-latest
+          - os: ubuntu-latest
             python-version: '3.12'
-            tags: cov
 
-          - name: intermediate supported version
-            os: ubuntu-latest
+          - os: ubuntu-latest
             python-version: '3.11'
             tags: cov
 
-          - name: oldest supported versions
-            os: ubuntu-latest
+          - os: ubuntu-latest
             python-version: '3.10'
 
-          - name: macOS
-            os: macos-latest
+          - os: macos-latest
             python-version: '3.11'
 
-          - name: Windows
-            os: windows-latest
+          - os: windows-latest
             python-version: '3.11'
             env:
               PYTHONIOENCODING: utf-8
@@ -120,13 +113,14 @@ jobs:
           echo "matrix test result: ${{ needs.test.result }}"
           echo "conda test result: ${{ needs.test-conda.result }}"
 
-      - name: Fail if any test failed
+      - name: Fail if any failed
         run: |
-          for j in test test-conda; do
-            r="${{ needs[$j].result }}"
-            if [ "$r" = "failure" ]; then
-              echo "$j failed!"
-              exit 1
-            fi
-          done
+          if [ "${{ needs.test.result }}" = "failure" ]; then
+            echo "❌ matrix test failed"
+            exit 1
+          fi
+          if [ "${{ needs['test-conda'].result }}" = "failure" ]; then
+            echo "❌ test-conda failed"
+            exit 1
+          fi
           echo "👍 All succeeded or skipped"
