Add `aggregate` that should be the only one `required`

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -29,29 +29,23 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - name: latest supported versions
-            os: ubuntu-latest
+          - os: ubuntu-latest
             python-version: '3.13'
 
-          - name: intermediate py3.12 version (cov)
-            os: ubuntu-latest
+          - os: ubuntu-latest
             python-version: '3.12'
             tags: cov
 
-          - name: intermediate py3.11 version
-            os: ubuntu-latest
+          - os: ubuntu-latest
             python-version: '3.11'
 
-          - name: oldest supported versions
-            os: ubuntu-latest
+          - os: ubuntu-latest
             python-version: '3.10'
 
-          - name: macOS latest
-            os: macos-latest
+          - os: macos-latest
             python-version: '3.11'
 
-          - name: Windows latest py3.11
-            os: windows-latest
+          - os: windows-latest
             python-version: '3.11'
             env:
               PYTHONIOENCODING: utf-8
@@ -107,3 +101,25 @@ jobs:
         shell: bash -el {0}
         run: |
           pytest -vv
+
+  aggregate:
+    needs: [test, test-conda]
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    name: 🛠 Aggregate test results
+    steps:
+      - name: Show individual results
+        run: |
+          echo "matrix test result: ${{ needs.test.result }}"
+          echo "conda test result: ${{ needs.test-conda.result }}"
+
+      - name: Fail if any test failed
+        run: |
+          for j in test test-conda; do
+            r="${{ needs[$j].result }}"
+            if [ "$r" = "failure" ]; then
+              echo "$j failed!"
+              exit 1
+            fi
+          done
+          echo "👍 All succeeded or skipped"
